name: origin-ui_local

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: deps
    container_name: origin-ui_app
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./next.config.ts:/app/next.config.ts
      - ./tsconfig.json:/app/tsconfig.json
      - ./postcss.config.mjs:/app/postcss.config.mjs
      - ./components.json:/app/components.json
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    command: npm run dev -- -H 0.0.0.0
    networks:
      - origin-ui-network

networks:
  origin-ui-network:
    driver: bridge
